API_CATEGORIES = {
    "Accreditations": [
        {"label": "List Accreditations", "value": "/v2/accreditations"},
        {"label": "Accreditation by ID", "value": "/v2/accreditations/:id"},
    ],
    "Achievements": [
        {"label": "List Achievements", "value": "/v2/achievements"},
        {"label": "Cursus Achievements", "value": "/v2/cursus/:cursus_id/achievements"},
        {"label": "Campus Achievements", "value": "/v2/campus/:campus_id/achievements"},
        {"label": "Title Achievements", "value": "/v2/titles/:title_id/achievements"},
        {"label": "Achievement by ID", "value": "/v2/achievements/:id"},
    ],
    "Achievements Users": [
        {"label": "Users Earned Achievement", "value": "/v2/achievements/:achievement_id/achievements_users"},
        {"label": "List Achievements Users", "value": "/v2/achievements_users"},
        {"label": "Achievements Users by ID", "value": "/v2/achievements_users/:id"},
    ],
    "Amendments": [
        {"label": "List Amendments", "value": "/v2/amendments"},
        {"label": "User Amendments", "value": "/v2/users/:user_id/amendments"},
        {"label": "Internship Amendments", "value": "/v2/internships/:internship_id/amendments"},
        {"label": "Amendment by ID", "value": "/v2/amendments/:id"},
    ],
    "Announcements": [
        {"label": "Announcements Graph", "value": "/v2/announcements/graph(/on/:field(/by/:interval))"},
        {"label": "Announcement by ID", "value": "/v2/announcements/:id"},
    ],
    "Apps": [
        {"label": "List Apps", "value": "/v2/apps"},
        {"label": "User Apps", "value": "/v2/users/:user_id/apps"},
        {"label": "App by ID", "value": "/v2/apps/:id"},
    ],
    "Attachments": [
        {"label": "Project Session Attachments", "value": "/v2/project_sessions/:project_session_id/attachments"},
        {"label": "Project Attachments", "value": "/v2/projects/:project_id/attachments"},
        {"label": "List Attachments", "value": "/v2/attachments"},
        {"label": "Project Session Attachment by ID", "value": "/v2/project_sessions/:project_session_id/attachments/:id"},
        {"label": "Attachment by ID", "value": "/v2/attachments/:id"},
    ],
    "Blocs": [
        {"label": "List Blocs", "value": "/v2/blocs"},
        {"label": "Bloc by ID", "value": "/v2/blocs/:id"},
    ],
    "Broadcasts": [
        {"label": "Campus Broadcasts", "value": "/v2/campus/:campus_id/broadcasts"},
    ],
    "Campus": [
        {"label": "List Campus", "value": "/v2/campus"},
        {"label": "Campus by ID", "value": "/v2/campus/:id"},
        {"label": "Campus Stats", "value": "/v2/campus/:campus_id/stats"},
    ],
    "Campus Users": [
        {"label": "List Campus Users", "value": "/v2/campus_users"},
        {"label": "User Campus Users", "value": "/v2/users/:user_id/campus_users"},
        {"label": "Campus User by ID", "value": "/v2/campus_users/:id"},
    ],
    "Coalitions": [
        {"label": "List Coalitions", "value": "/v2/coalitions"},
        {"label": "User Coalitions", "value": "/v2/users/:user_id/coalitions"},
        {"label": "Bloc Coalitions", "value": "/v2/blocs/:bloc_id/coalitions"},
        {"label": "Coalition by ID", "value": "/v2/coalitions/:id"},
    ],
    "Coalitions Users": [
        {"label": "Coalition Users by Coalition ID", "value": "/v2/coalitions/:coalition_id/coalitions_users"},
        {"label": "List Coalitions Users", "value": "/v2/coalitions_users"},
        {"label": "User Coalitions Users", "value": "/v2/users/:user_id/coalitions_users"},
        {"label": "Coalition User by ID", "value": "/v2/coalitions_users/:id"},
    ],
    "Commands": [
        {"label": "Product Commands", "value": "/v2/products/:product_id/commands"},
        {"label": "Campus Product Commands", "value": "/v2/campus/:campus_id/products/:product_id/commands"},
    ],
    "Community Services": [
        {"label": "Community Services Graph", "value": "/v2/community_services/graph(/on/:field(/by/:interval))"},
        {"label": "Close Community Services", "value": "/v2/closes/:close_id/community_services"},
        {"label": "List Community Services", "value": "/v2/community_services"},
        {"label": "Community Service by ID", "value": "/v2/community_services/:id"},
    ],
    "Correction Point Historics": [
        {"label": "User Correction Point Historics", "value": "/v2/users/:user_id/correction_point_historics"},
    ],
    "Cursus": [
        {"label": "List Cursus", "value": "/v2/cursus"},
        {"label": "Cursus by ID", "value": "/v2/cursus/:id"},
    ],
    "Cursus Users": [
        {"label": "Cursus Users Graph", "value": "/v2/cursus_users/graph(/on/:field(/by/:interval))"},
        {"label": "List Cursus Users", "value": "/v2/cursus_users"},
        {"label": "User Cursus Users", "value": "/v2/users/:user_id/cursus_users"},
        {"label": "Cursus Users by Cursus ID", "value": "/v2/cursus/:cursus_id/cursus_users"},
        {"label": "Cursus User by ID", "value": "/v2/cursus_users/:id"},
    ],
    "Dashes": [
        {"label": "Dashes Graph", "value": "/v2/dashes/graph(/on/:field(/by/:interval))"},
    ],
    "Dashes Users": [
        {"label": "Dashes Users Graph", "value": "/v2/dashes_users/graph(/on/:field(/by/:interval))"},
        {"label": "List Dashes Users", "value": "/v2/dashes_users"},
        {"label": "Dash Users by Dash ID", "value": "/v2/dashes/:dash_id/dashes_users"},
        {"label": "Dash User by ID", "value": "/v2/dashes_users/:id"},
    ],
    "Events": [
        {"label": "Events Graph", "value": "/v2/events/graph(/on/:field(/by/:interval))"},
        {"label": "Cursus Events", "value": "/v2/cursus/:cursus_id/events"},
        {"label": "Campus Events", "value": "/v2/campus/:campus_id/events"},
        {"label": "Campus Cursus Events", "value": "/v2/campus/:campus_id/cursus/:cursus_id/events"},
        {"label": "User Events", "value": "/v2/users/:user_id/events"},
        {"label": "List Events", "value": "/v2/events"},
        {"label": "Event by ID", "value": "/v2/events/:id"},
    ],
    "Events Users": [
        {"label": "User Event Registrations", "value": "/v2/users/:user_id/events_users"},
        {"label": "Event Registrations by Event ID", "value": "/v2/events/:event_id/events_users"},
        {"label": "List Events Users", "value": "/v2/events_users"},
        {"label": "Event User by ID", "value": "/v2/events_users/:id"},
        {"label": "Register User to Event", "value": "POST /v2/events_users"},
        {"label": "Update Event User", "value": "PATCH /v2/events_users/:id"},
        {"label": "Replace Event User", "value": "PUT /v2/events_users/:id"},
        {"label": "Delete Event User", "value": "DELETE /v2/events_users/:id"},
    ],
    "Exams": [
        {"label": "Exams Graph", "value": "/v2/exams/graph(/on/:field(/by/:interval))"},
        {"label": "Cursus Exams", "value": "/v2/cursus/:cursus_id/exams"},
        {"label": "Campus Exams", "value": "/v2/campus/:campus_id/exams"},
        {"label": "Campus Cursus Exams", "value": "/v2/campus/:campus_id/cursus/:cursus_id/exams"},
        {"label": "User Exams", "value": "/v2/users/:user_id/exams"},
        {"label": "Project Exams", "value": "/v2/projects/:project_id/exams"},
        {"label": "List Exams", "value": "/v2/exams"},
        {"label": "Exam by ID", "value": "/v2/exams/:id"},
    ],
    "Expertises": [
        {"label": "List Expertises", "value": "/v2/expertises"},
        {"label": "Expertise by ID", "value": "/v2/expertises/:id"},
    ],
    "Expertises Users": [
        {"label": "Expertise Users by Expertise ID", "value": "/v2/expertises/:expertise_id/expertises_users"},
        {"label": "User Expertise", "value": "/v2/users/:user_id/expertises_users"},
        {"label": "List Expertise Users", "value": "/v2/expertises_users"},
        {"label": "Expertise User by ID", "value": "/v2/expertises_users/:id"},
        {"label": "Add User to Expertise", "value": "POST /v2/expertises/:expertise_id/expertises_users"},
        {"label": "Add Expertise to User", "value": "POST /v2/users/:user_id/expertises_users"},
        {"label": "Add Expertise User", "value": "POST /v2/expertises_users"},
        {"label": "Update Expertise User", "value": "PATCH /v2/expertises_users/:id"},
        {"label": "Replace Expertise User", "value": "PUT /v2/expertises_users/:id"},
        {"label": "Delete Expertise User", "value": "DELETE /v2/expertises_users/:id"},
    ],
    "Feedbacks": [
        {"label": "Event Feedbacks", "value": "/v2/events/:event_id/feedbacks"},
        {"label": "List Feedbacks", "value": "/v2/feedbacks"},
        {"label": "Scale Team Feedbacks", "value": "/v2/scale_teams/:scale_team_id/feedbacks"},
        {"label": "Event Feedback by ID", "value": "/v2/events/:event_id/feedbacks/:id"},
        {"label": "Feedback by ID", "value": "/v2/feedbacks/:id"},
        {"label": "Scale Team Feedback by ID", "value": "/v2/scale_teams/:scale_team_id/feedbacks/:id"},
        {"label": "Create Event Feedback", "value": "POST /v2/events/:event_id/feedbacks"},
        {"label": "Create Feedback", "value": "POST /v2/feedbacks"},
        {"label": "Create Scale Team Feedback", "value": "POST /v2/scale_teams/:scale_team_id/feedbacks"},
        {"label": "Update Event Feedback", "value": "PATCH /v2/events/:event_id/feedbacks/:id"},
        {"label": "Replace Event Feedback", "value": "PUT /v2/events/:event_id/feedbacks/:id"},
        {"label": "Update Feedback", "value": "PATCH /v2/feedbacks/:id"},
        {"label": "Replace Feedback", "value": "PUT /v2/feedbacks/:id"},
        {"label": "Update Scale Team Feedback", "value": "PATCH /v2/scale_teams/:scale_team_id/feedbacks/:id"},
        {"label": "Replace Scale Team Feedback", "value": "PUT /v2/scale_teams/:scale_team_id/feedbacks/:id"},
        {"label": "Delete Event Feedback", "value": "DELETE /v2/events/:event_id/feedbacks/:id"},
        {"label": "Delete Feedback", "value": "DELETE /v2/feedbacks/:id"},
        {"label": "Delete Scale Team Feedback", "value": "DELETE /v2/scale_teams/:scale_team_id/feedbacks/:id"},
    ],
    "Flags": [
        {"label": "List Flags", "value": "/v2/flags"},
    ],
    "Groups": [
        {"label": "List Groups", "value": "/v2/groups"},
        {"label": "User Groups", "value": "/v2/users/:user_id/groups"},
        {"label": "Group by ID", "value": "/v2/groups/:id"},
    ],
    "Groups Users": [
        {"label": "List Group Users", "value": "/v2/groups_users"},
        {"label": "Group Users by Group ID", "value": "/v2/groups/:group_id/groups_users"},
        {"label": "User Group Users", "value": "/v2/users/:user_id/groups_users"},
        {"label": "Group User by ID", "value": "/v2/groups_users/:id"},
    ],
    "Languages": [
        {"label": "Languages Graph", "value": "/v2/languages/graph(/on/:field(/by/:interval))"},
        {"label": "List Languages", "value": "/v2/languages"},
        {"label": "Language by ID", "value": "/v2/languages/:id"},
    ],
    "Languages Users": [
        {"label": "Languages Users Graph", "value": "/v2/languages_users/graph(/on/:field(/by/:interval))"},
        {"label": "User Languages", "value": "/v2/users/:user_id/languages_users"},
        {"label": "List Languages Users", "value": "/v2/languages_users"},
        {"label": "User Language by ID", "value": "/v2/users/:user_id/languages_users/:id"},
        {"label": "Language User by ID", "value": "/v2/languages_users/:id"},
    ],
    "Locations": [
        {"label": "Locations Graph", "value": "/v2/locations/graph(/on/:field(/by/:interval))"},
        {"label": "List Locations", "value": "/v2/locations"},
        {"label": "User Locations", "value": "/v2/users/:user_id/locations"},
        {"label": "Campus Locations", "value": "/v2/campus/:campus_id/locations"},
        {"label": "Location by ID", "value": "/v2/locations/:id"},
    ],
    "Notes": [
        {"label": "User Notes", "value": "/v2/users/:user_id/notes"},
        {"label": "Campus Notes", "value": "/v2/campus/:campus_id/notes"},
        {"label": "List Notes", "value": "/v2/notes"},
        {"label": "Note by ID", "value": "/v2/notes/:id"},
        {"label": "Create Note", "value": "POST /v2/notes"},
        {"label": "Update Note", "value": "PATCH /v2/notes/:id"},
        {"label": "Replace Note", "value": "PUT /v2/notes/:id"},
        {"label": "Delete Note", "value": "DELETE /v2/notes/:id"},
    ],
    "Notions": [
        {"label": "Cursus Notions", "value": "/v2/cursus/:cursus_id/notions"},
        {"label": "Tag Notions", "value": "/v2/tags/:tag_id/notions"},
        {"label": "List Notions", "value": "/v2/notions"},
        {"label": "Notion by ID", "value": "/v2/notions/:id"},
    ],
    "Offers": [
        {"label": "List Offers", "value": "/v2/offers"},
        {"label": "Offer by ID", "value": "/v2/offers/:id"},
    ],
    "Partnerships": [
        {"label": "List Partnerships", "value": "/v2/partnerships"},
        {"label": "Partnership by ID", "value": "/v2/partnerships/:id"},
    ],
    "Partnerships Users": [
        {"label": "Partnership Users by Partnership ID", "value": "/v2/partnerships/:partnership_id/partnerships_users"},
        {"label": "List Partnerships Users", "value": "/v2/partnerships_users"},
        {"label": "Partnership User by ID", "value": "/v2/partnerships_users/:id"},
    ],
    "Patronages Reports": [
        {"label": "Patronages Reports Graph", "value": "/v2/patronages_reports/graph(/on/:field(/by/:interval))"},
    ],
    "Products": [
        {"label": "List Products", "value": "/v2/products"},
        {"label": "Campus Products", "value": "/v2/campus/:campus_id/products"},
        {"label": "Product by ID", "value": "/v2/products/:id"},
        {"label": "Campus Product by ID", "value": "/v2/campus/:campus_id/products/:id"},
    ],
    "Project Data": [
        {"label": "List Project Data", "value": "/v2/project_data"},
        {"label": "Project Data by Project Session ID", "value": "/v2/project_sessions/:project_session_id/project_data"},
        {"label": "Project Data by ID", "value": "/v2/project_data/:id"},
    ],
    "Project Sessions": [
        {"label": "Project Sessions Graph by Project ID", "value": "/v2/projects/:project_id/project_sessions/graph(/on/:field(/by/:interval))"},
        {"label": "Project Sessions Graph", "value": "/v2/project_sessions/graph(/on/:field(/by/:interval))"},
        {"label": "Project Sessions by Project ID", "value": "/v2/projects/:project_id/project_sessions"},
        {"label": "List Project Sessions", "value": "/v2/project_sessions"},
        {"label": "Project Session by ID", "value": "/v2/project_sessions/:id"},
    ],
    "Project Sessions Skills": [
        {"label": "List Project Sessions Skills", "value": "/v2/project_sessions_skills"},
        {"label": "Project Session Skills by Session ID", "value": "/v2/project_sessions/:project_session_id/project_sessions_skills"},
        {"label": "Project Session Skills by Skill ID", "value": "/v2/skills/:skill_id/project_sessions_skills"},
        {"label": "Project Session Skill by ID", "value": "/v2/project_sessions_skills/:id"},
        {"label": "Project Session Skill by Session and ID", "value": "/v2/project_sessions/:project_session_id/project_sessions_skills/:id"},
    ],
    "Projects": [
        {"label": "Cursus Projects", "value": "/v2/cursus/:cursus_id/projects"},
        {"label": "Project by ID", "value": "/v2/projects/:project_id/projects"},
        {"label": "List Projects", "value": "/v2/projects"},
        {"label": "My Projects", "value": "/v2/me/projects"},
        {"label": "Project Details", "value": "/v2/projects/:id"},
        {"label": "Retry Project (PATCH)", "value": "PATCH /v2/projects/:id/retry"},
        {"label": "Retry Project (PUT)", "value": "PUT /v2/projects/:id/retry"},
    ],
    "Projects Users": [
        {"label": "Projects Users Graph by Project", "value": "/v2/projects/:project_id/projects_users/graph(/on/:field(/by/:interval))"},
        {"label": "Projects Users Graph by User", "value": "/v2/users/:user_id/projects_users/graph(/on/:field(/by/:interval))"},
        {"label": "Projects Users Graph", "value": "/v2/projects_users/graph(/on/:field(/by/:interval))"},
        {"label": "Projects Users by Project", "value": "/v2/projects/:project_id/projects_users"},
        {"label": "Projects Users by User", "value": "/v2/users/:user_id/projects_users"},
        {"label": "List Projects Users", "value": "/v2/projects_users"},
        {"label": "Project User by ID", "value": "/v2/projects_users/:id"},
        {"label": "Register User to Project", "value": "POST /v2/projects/:project_id/projects_users"},
        {"label": "Register User to Projects", "value": "POST /v2/users/:user_id/projects_users"},
        {"label": "Create Project User", "value": "POST /v2/projects_users"},
        {"label": "Register to Project", "value": "POST /v2/projects/:project_id/register"},
        {"label": "Delete Project User", "value": "DELETE /v2/projects_users/:id"},
        {"label": "Compile Project User (PATCH)", "value": "PATCH /v2/projects_users/:id/compile"},
        {"label": "Compile Project User (PUT)", "value": "PUT /v2/projects_users/:id/compile"},
        {"label": "Retry Project User (PATCH)", "value": "PATCH /v2/projects_users/:id/retry"},
        {"label": "Retry Project User (PUT)", "value": "PUT /v2/projects_users/:id/retry"},
        {"label": "Register Childs and Scales", "value": "POST /v2/projects_users/register_childs_and_scales"},
        {"label": "Reset Project Users", "value": "DELETE /v2/projects_users/reset"},
        {"label": "Scale Project Users", "value": "PATCH /v2/projects_users/scale"},
    ],
    "Quests Users": [
        {"label": "Quests Users Graph", "value": "/v2/quests_users/graph(/on/:field(/by/:interval))"},
        {"label": "Quests Users by Quest", "value": "/v2/quests/:quest_id/quests_users"},
        {"label": "Quests Users by User", "value": "/v2/users/:user_id/quests_users"},
        {"label": "List Quests Users", "value": "/v2/quests_users"},
        {"label": "Quest User by ID", "value": "/v2/quests_users/:id"},
    ],
    "Roles": [
        {"label": "List Roles", "value": "/v2/roles"},
        {"label": "User Roles", "value": "/v2/users/:user_id/roles"},
        {"label": "Role by ID", "value": "/v2/roles/:id"},
    ],
    "Roles Entities": [
        {"label": "Roles Entities Graph", "value": "/v2/roles_entities/graph(/on/:field(/by/:interval))"},
        {"label": "Roles Entities by Role", "value": "/v2/roles/:role_id/roles_entities"},
        {"label": "List Roles Entities", "value": "/v2/roles_entities"},
        {"label": "Role Entity by ID", "value": "/v2/roles_entities/:id"},
    ],
    "Scale Teams": [
        {"label": "Scale Teams Graph", "value": "/v2/scale_teams/graph(/on/:field(/by/:interval))"},
        {"label": "Project Scale Teams Graph", "value": "/v2/projects/:project_id/scale_teams/graph(/on/:field(/by/:interval))"},
        {"label": "User Scale Teams Graph", "value": "/v2/users/:user_id/scale_teams/graph(/on/:field(/by/:interval))"},
        {"label": "Project Session Scale Teams", "value": "/v2/project_sessions/:project_session_id/scale_teams"},
        {"label": "List Scale Teams", "value": "/v2/scale_teams"},
        {"label": "Project Scale Teams", "value": "/v2/projects/:project_id/scale_teams"},
        {"label": "User Scale Teams (as Corrector)", "value": "/v2/users/:user_id/scale_teams/as_corrector"},
        {"label": "User Scale Teams (as Corrected)", "value": "/v2/users/:user_id/scale_teams/as_corrected"},
        {"label": "User Scale Teams", "value": "/v2/users/:user_id/scale_teams"},
        {"label": "My Scale Teams (as Corrector)", "value": "/v2/me/scale_teams/as_corrector"},
        {"label": "My Scale Teams (as Corrected)", "value": "/v2/me/scale_teams/as_corrected"},
        {"label": "My Scale Teams", "value": "/v2/me/scale_teams"},
        {"label": "Scale Team by Project Session", "value": "/v2/project_sessions/:project_session_id/scale_teams/:id"},
        {"label": "Scale Team by ID", "value": "/v2/scale_teams/:id"},
        {"label": "Create Scale Team", "value": "POST /v2/scale_teams"},
        {"label": "Update Scale Team (PATCH)", "value": "PATCH /v2/scale_teams/:id"},
        {"label": "Replace Scale Team (PUT)", "value": "PUT /v2/scale_teams/:id"},
        {"label": "Delete Scale Team", "value": "DELETE /v2/scale_teams/:id"},
    ],
    "Skills": [
        {"label": "List Skills", "value": "/v2/skills"},
        {"label": "Cursus Skills", "value": "/v2/cursus/:cursus_id/skills"},
        {"label": "Skill by ID", "value": "/v2/skills/:id"},
    ],
    "Slots": [
        {"label": "Slots Graph", "value": "/v2/slots/graph(/on/:field(/by/:interval))"},
        {"label": "Project Slots Graph", "value": "/v2/projects/:project_id/slots/graph(/on/:field(/by/:interval))"},
        {"label": "User Slots Graph", "value": "/v2/users/:user_id/slots/graph(/on/:field(/by/:interval))"},
        {"label": "List Slots", "value": "/v2/slots"},
        {"label": "Project Slots", "value": "/v2/projects/:project_id/slots"},
        {"label": "User Slots", "value": "/v2/users/:user_id/slots"},
        {"label": "My Slots", "value": "/v2/me/slots"},
        {"label": "Slot by ID", "value": "/v2/slots/:id"},
        {"label": "Create Slot", "value": "POST /v2/slots"},
        {"label": "Update Slot (PATCH)", "value": "PATCH /v2/slots/:id"},
        {"label": "Replace Slot (PUT)", "value": "PUT /v2/slots/:id"},
        {"label": "Delete Slot", "value": "DELETE /v2/slots/:id"},
    ],
    "Subnotions": [
        {"label": "Subnotions by Notion", "value": "/v2/notions/:notion_id/subnotions"},
        {"label": "List Subnotions", "value": "/v2/subnotions"},
        {"label": "Subnotion by ID", "value": "/v2/subnotions/:id"},
    ],
    "Tags": [
        {"label": "Project Tags", "value": "/v2/projects/:project_id/tags"},
        {"label": "Issue Tags", "value": "/v2/issues/:issue_id/tags"},
        {"label": "Notion Tags", "value": "/v2/notions/:notion_id/tags"},
        {"label": "Cursus Tags", "value": "/v2/cursus/:cursus_id/tags"},
        {"label": "User Tags", "value": "/v2/users/:user_id/tags"},
        {"label": "List Tags", "value": "/v2/tags"},
        {"label": "Tag by ID", "value": "/v2/tags/:id"},
    ],
    "Tags Users": [
        {"label": "List Tags Users", "value": "/v2/tags_users"},
        {"label": "Tags by User", "value": "/v2/users/:user_id/tags_users"},
        {"label": "Tags Users by Cursus", "value": "/v2/cursus/:cursus_id/tags_users"},
        {"label": "Tags Users by Campus", "value": "/v2/campus/:campus_id/tags_users"},
        {"label": "Tags Users by Tag", "value": "/v2/tags/:tag_id/tags_users"},
        {"label": "Tags User by ID", "value": "/v2/tags_users/:id"},
    ],
    "Teams": [
        {"label": "Teams Graph by Cursus", "value": "/v2/cursus/:cursus_id/teams/graph(/on/:field(/by/:interval))"},
        {"label": "Teams Graph by User", "value": "/v2/users/:user_id/teams/graph(/on/:field(/by/:interval))"},
        {"label": "Teams Graph by User and Project", "value": "/v2/users/:user_id/projects/:project_id/teams/graph(/on/:field(/by/:interval))"},
        {"label": "Teams Graph", "value": "/v2/teams/graph(/on/:field(/by/:interval))"},
        {"label": "Teams Graph by Project", "value": "/v2/projects/:project_id/teams/graph(/on/:field(/by/:interval))"},
        {"label": "List Teams by Cursus", "value": "/v2/cursus/:cursus_id/teams"},
        {"label": "List Teams by User", "value": "/v2/users/:user_id/teams"},
        {"label": "List Teams by User and Project", "value": "/v2/users/:user_id/projects/:project_id/teams"},
        {"label": "List Teams", "value": "/v2/teams"},
        {"label": "List Teams by Project", "value": "/v2/projects/:project_id/teams"},
        {"label": "List Teams by Project Session", "value": "/v2/project_sessions/:project_session_id/teams"},
        {"label": "My Teams", "value": "/v2/me/teams"},
        {"label": "Team by ID", "value": "/v2/teams/:id"},
        {"label": "Create Team", "value": "POST /v2/teams"},
        {"label": "Update Team", "value": "PATCH /v2/teams/:id"},
        {"label": "Replace Team", "value": "PUT /v2/teams/:id"},
        {"label": "Delete Team", "value": "DELETE /v2/teams/:id"},
        {"label": "Reset Team Uploads", "value": "POST /v2/teams/:id/reset_team_uploads"},
    ],
    "Teams Uploads": [
        {"label": "List Team Uploads", "value": "/v2/teams_uploads"},
        {"label": "Team Uploads by Team ID", "value": "/v2/teams/:team_id/teams_uploads"},
        {"label": "Team Upload by ID", "value": "/v2/teams_uploads/:id"},
    ],
    "Teams Users": [
        {"label": "List Teams Users", "value": "/v2/teams_users"},
        {"label": "Teams Users by User", "value": "/v2/users/:user_id/teams_users"},
        {"label": "Teams Users by Team", "value": "/v2/teams/:team_id/teams_users"},
        {"label": "Team User by ID", "value": "/v2/teams_users/:id"},
    ],
    "Titles": [
        {"label": "List Titles", "value": "/v2/titles"},
        {"label": "User Titles", "value": "/v2/users/:user_id/titles"},
        {"label": "Title by ID", "value": "/v2/titles/:id"},
    ],
    "Titles Users": [
        {"label": "Titles Users by Title", "value": "/v2/titles/:title_id/titles_users"},
        {"label": "Titles Users by User", "value": "/v2/users/:user_id/titles_users"},
        {"label": "List Titles Users", "value": "/v2/titles_users"},
        {"label": "Title User by ID", "value": "/v2/titles_users/:id"},
    ],
    "Translations": [
        {"label": "List Translations", "value": "/v2/translations"},
        {"label": "Translation by ID", "value": "/v2/translations/:id"},
    ],
    "Users": [
        {"label": "Users Graph", "value": "/v2/users/graph(/on/:field(/by/:interval))"},
        {"label": "User Locations Stats", "value": "/v2/users/:id/locations_stats"},
        {"label": "Users by Coalition", "value": "/v2/coalitions/:coalition_id/users"},
        {"label": "Users by Dash", "value": "/v2/dashes/:dash_id/users"},
        {"label": "Users by Event", "value": "/v2/events/:event_id/users"},
        {"label": "Users by Accreditation", "value": "/v2/accreditations/:accreditation_id/users"},
        {"label": "Users by Team", "value": "/v2/teams/:team_id/users"},
        {"label": "Users by Project", "value": "/v2/projects/:project_id/users"},
        {"label": "Users by Partnership", "value": "/v2/partnerships/:partnership_id/users"},
        {"label": "Users by Expertise", "value": "/v2/expertises/:expertise_id/users"},
        {"label": "List Users", "value": "/v2/users"},
        {"label": "Users by Cursus", "value": "/v2/cursus/:cursus_id/users"},
        {"label": "Users by Campus", "value": "/v2/campus/:campus_id/users"},
        {"label": "Users by Achievement", "value": "/v2/achievements/:achievement_id/users"},
        {"label": "Users by Title", "value": "/v2/titles/:title_id/users"},
        {"label": "Users by Quest", "value": "/v2/quests/:quest_id/users"},
        {"label": "Users by Group", "value": "/v2/groups/:group_id/users"},
        {"label": "User by ID", "value": "/v2/users/:id"},
        {"label": "My Profile", "value": "/v2/me"},
    ],
}